apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    project: flipkart  
  tolerations:
  - key: "project"      
    operator: "Equal"
    value: "flipkart"
    effect: "NoSchedule"